### ISSUE TITLE
Can't make any morningstar functions to work

### ISSUE THREAD

**Issue by gaurav811** [madsailor/SMF-Extension#2]
I have Windows 7 64 bit + LibreOffice 4.4.1 and LibreOffice 4.3.6 installed. I tried both v6.4 and v6.3 of the sfm extension with both the Libreoffice version. In none of the case I was able to make the example Morningstar files. Yahoo works for all versions and I am able to update the data but all I see is NMS or NYQ in the data column

**Comment by madsailor** [comment]
Thanks for reporting this.  It looks like Yahoo changed 'NYSE' to 'NYQ' to report the exchange, which breaks SMF since the exchange that a ticker is traded on is needed in order to query Morningstar.  I will look at changing the code, or looking for a more robust way to look up exchanges and post an update to the extension as soon as I have a chance.

**Comment by madsailor** [comment]
New version 0.7.0 is up.  Exchange lookup has migrated from Yahoo to NASDAQ, so it should be much more stable.
